# Generated by Django 4.0.1 on 2022-02-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='site_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
